const state={products:[],cart:JSON.parse(localStorage.getItem('vd_cart')||'[]'),favorites:JSON.parse(localStorage.getItem('vd_favorites')||'[]'),category:'Összes',search:''};
const $=s=>document.querySelector(s);
const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function saveCart(){localStorage.setItem('vd_cart',JSON.stringify(state.cart));renderCart()}
function saveFavorites(){localStorage.setItem('vd_favorites',JSON.stringify(state.favorites))}
function isFavorite(id){return state.favorites.includes(Number(id))}
function toggleFavorite(id){id=Number(id);state.favorites=isFavorite(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveFavorites();renderProducts();toast(isFavorite(id)?'Hozzáadva a kedvencekhez':'Eltávolítva a kedvencekből')}
function filteredProducts(){return state.products.filter(p=>{const catOk=state.category==='Összes'||p.category===state.category;const q=state.search.trim().toLowerCase();const searchOk=!q||`${p.title} ${p.creator} ${p.category}`.toLowerCase().includes(q);return catOk&&searchOk})}
function renderProducts(){const el=$('#products');if(!el)return;const list=filteredProducts();if(!list.length){el.innerHTML='<div class="empty" style="grid-column:1/-1;padding:40px;text-align:center">Nincs találat. Próbálj más keresést vagy kategóriát.</div>';return}el.innerHTML=list.map(p=>`<article class="card"><div class="productImg" onclick="productDetail(${p.id})" style="cursor:pointer;position:relative">${p.emoji||'✦'}<button class="icon" aria-label="Kedvenc" onclick="event.stopPropagation();toggleFavorite(${p.id})" style="position:absolute;right:12px;top:12px">${isFavorite(p.id)?'♥':'♡'}</button></div><div class="cardBody"><div class="meta"><span>${p.category}</span><span>${p.verified?'✓ Verified':''}</span></div><h3>${p.title}</h3><div class="meta"><span>${p.creator}</span><span class="price">€${Number(p.price).toFixed(2)}</span></div><div class="meta"><span>${p.stock<=3?`Csak ${p.stock} db`:'Készleten'}</span></div><div class="row" style="margin-top:12px"><button class="ghost" style="flex:1" onclick="productDetail(${p.id})">Részletek</button><button class="primary buy" style="flex:1" onclick="add(${p.id})">Kosárba</button></div></div></article>`).join('')}
function add(id){const p=state.products.find(x=>Number(x.id)===Number(id));if(!p)return;const old=state.cart.find(x=>Number(x.id)===Number(id));if(old){if(old.qty>=p.stock)return toast('Nincs több készleten');old.qty++}else state.cart.push({id:p.id,title:p.title,creator:p.creator,price:p.price,qty:1});saveCart();toast('Termék hozzáadva a kosárhoz')}
function changeQty(id,delta){const item=state.cart.find(x=>Number(x.id)===Number(id));if(!item)return;const p=state.products.find(x=>Number(x.id)===Number(id));item.qty+=delta;if(p&&item.qty>p.stock)item.qty=p.stock;if(item.qty<=0)state.cart=state.cart.filter(x=>Number(x.id)!==Number(id));saveCart()}
function renderCart(){const count=state.cart.reduce((a,x)=>a+x.qty,0);if($('#cartCount'))$('#cartCount').textContent=count;if($('#cartItems'))$('#cartItems').innerHTML=state.cart.length?state.cart.map(x=>`<div class="cartRow"><div style="flex:1"><b>${x.title}</b><div class="meta">${x.creator}</div><div class="row" style="margin-top:7px"><button class="ghost" onclick="changeQty(${x.id},-1)">−</button><span style="padding:8px 12px">${x.qty}</span><button class="ghost" onclick="changeQty(${x.id},1)">+</button></div></div><strong>€${(x.price*x.qty).toFixed(2)}</strong></div>`).join(''):'<div class="empty">A kosarad még üres.</div>';if($('#cartTotal'))$('#cartTotal').textContent='€'+state.cart.reduce((a,x)=>a+x.price*x.qty,0).toFixed(2)}
function openDrawer(){$('#drawer')?.classList.add('open');$('#backdrop')?.classList.add('show')}function closeDrawer(){$('#drawer')?.classList.remove('open');$('#backdrop')?.classList.remove('show')}
function showModal(html){$('#modalRoot').innerHTML=`<div class="overlay" id="modalOverlay">${html}</div>`}function closeModal(){$('#modalRoot').innerHTML=''}
function productDetail(id){const p=state.products.find(x=>Number(x.id)===Number(id));if(!p)return;showModal(`<div class="modal"><div class="productImg" style="height:220px;margin-bottom:20px">${p.emoji||'✦'}</div><div class="eyebrow">${p.category} • ${p.verified?'VERIFIED CREATOR':''}</div><h2>${p.title}</h2><p class="muted">Creator: <strong>${p.creator}</strong></p><div class="row" style="justify-content:space-between;align-items:center;margin:20px 0"><strong class="price" style="font-size:24px">€${Number(p.price).toFixed(2)}</strong><span>${p.stock<=3?`Csak ${p.stock} db maradt`:`${p.stock} db készleten`}</span></div><p class="muted">Limitált marketplace drop. A termék elérhetősége és készlete rendeléskor kerül ellenőrzésre.</p><button class="primary big full" onclick="closeModal();add(${p.id})">Kosárba teszem</button></div>`)}
function creatorProfile(name){const products=state.products.filter(p=>p.creator===name);showModal(`<div class="modal"><div class="eyebrow">VERIFIED CREATOR</div><h2>${name}</h2><p class="muted">Creator storefront • limitált dropok • diszkrét fulfillment</p><div style="margin:18px 0"><b>${products.length}</b> aktív termék</div><div class="steps">${products.slice(0,4).map(p=>`<div><b>${p.category}</b><h3>${p.title}</h3><p>€${Number(p.price).toFixed(2)}</p></div>`).join('')}</div><button class="primary big full" onclick="closeModal()">Bezárás</button></div>`)}
function login(){showModal(`<div class="modal"><h2>Belépés</h2><p class="muted">A teljes fiókrendszer a következő fejlesztési szakaszban kerül be.</p><form class="form" id="loginForm"><label>E-mail</label><input required type="email" placeholder="you@example.com"><label>Jelszó</label><input required type="password"><button class="primary big full">Demo belépés</button></form></div>`);$('#loginForm').onsubmit=e=>{e.preventDefault();closeModal();toast('Demo belépés sikeres')}}
function creatorApply(){showModal(`<div class="modal"><h2>Creator jelentkezés</h2><p>Az éles platformon KYC, 18+ ellenőrzés és tartalommoderáció szükséges.</p><form class="form" id="creatorForm"><label>Megjelenő név</label><input required><label>E-mail</label><input required type="email"><label>Social profil</label><input required placeholder="https://..."><button class="primary big full">Jelentkezés beküldése</button></form></div>`);$('#creatorForm').onsubmit=async e=>{e.preventDefault();const i=e.target.querySelectorAll('input');try{const r=await fetch('/api/creators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:i[0].value,email:i[1].value,social:i[2].value})});if(!r.ok)throw new Error();closeModal();toast('Jelentkezés elküldve')}catch{closeModal();toast('A jelentkezés demo módban elküldve')}}}
async function checkout(){if(!state.cart.length)return toast('A kosár üres');showModal(`<div class="modal"><h2>Rendelés összesítése</h2><p class="muted">Ez továbbra is demo checkout. Valódi fizetés nincs bekötve.</p><div class="cartRow"><span>Termékek</span><strong>${state.cart.reduce((a,x)=>a+x.qty,0)} db</strong></div><div class="cartRow"><span>Összesen</span><strong>€${state.cart.reduce((a,x)=>a+x.price*x.qty,0).toFixed(2)}</strong></div><form class="form" id="checkoutForm"><label>E-mail</label><input required type="email" placeholder="you@example.com"><label>Ország</label><select><option>Magyarország</option><option>Németország</option><option>Ausztria</option></select><button class="primary big full">Demo rendelés leadása</button></form></div>`);$('#checkoutForm').onsubmit=async e=>{e.preventDefault();const email=e.target.querySelector('input').value;try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,items:state.cart})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Hiba');state.cart=[];saveCart();closeModal();closeDrawer();toast('Rendelés létrehozva: '+d.orderId)}catch(err){toast(err.message||'Rendelési hiba')}}}
function setupMarketplaceTools(){const head=document.querySelector('#shop .sectionHead');if(!head||document.querySelector('#marketTools'))return;const tools=document.createElement('div');tools.id='marketTools';tools.style.cssText='display:flex;gap:10px;flex-wrap:wrap;margin-top:14px';tools.innerHTML=`<input id="marketSearch" type="search" placeholder="Keresés termékre vagy creatorra…" style="min-width:240px;flex:1;padding:12px 14px;border-radius:10px;border:1px solid #444;background:transparent;color:inherit"><button class="ghost" id="favoritesBtn">♡ Kedvencek</button>`;head.appendChild(tools);$('#marketSearch').oninput=e=>{state.search=e.target.value;renderProducts()};$('#favoritesBtn').onclick=()=>{const favs=state.products.filter(p=>isFavorite(p.id));if(!favs.length)return toast('Még nincs kedvenced');const el=$('#products');el.innerHTML=favs.map(p=>`<article class="card"><div class="productImg" onclick="productDetail(${p.id})" style="cursor:pointer">${p.emoji||'✦'}</div><div class="cardBody"><div class="meta"><span>${p.category}</span><span>♥</span></div><h3>${p.title}</h3><div class="meta"><span>${p.creator}</span><span class="price">€${Number(p.price).toFixed(2)}</span></div><button class="primary full" onclick="add(${p.id})">Kosárba</button></div></article>`).join('');toast(`${favs.length} kedvenc termék`)}}
$('#enter')?.addEventListener('click',()=>{localStorage.setItem('vd_age','1');$('#ageGate')?.remove()});$('#leave')?.addEventListener('click',()=>{document.body.innerHTML='<main style="padding:15vh 8vw;text-align:center"><h1>Viszlát.</h1><p>Az oldal használatához 18+ életkor szükséges.</p></main>'});if(localStorage.getItem('vd_age'))$('#ageGate')?.remove();
$('#cartBtn')?.addEventListener('click',openDrawer);$('#loginBtn')?.addEventListener('click',login);$('#creatorBtn')?.addEventListener('click',creatorApply);
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.cat;renderProducts()}));
fetch('/api/products').then(r=>r.json()).then(d=>{state.products=d;setupMarketplaceTools();renderProducts();renderCart()}).catch(()=>{state.products=[];setupMarketplaceTools();renderProducts();renderCart()});
