const state={products:[],cart:JSON.parse(localStorage.getItem('vd_cart')||'[]')};
const $=s=>document.querySelector(s);const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function save(){localStorage.setItem('vd_cart',JSON.stringify(state.cart));renderCart()}
function renderProducts(cat='Összes'){const el=$('#products');const list=cat==='Összes'?state.products:state.products.filter(p=>p.category===cat);el.innerHTML=list.map(p=>`<article class="card"><div class="productImg">${p.emoji}</div><div class="cardBody"><div class="meta"><span>${p.category}</span><span>${p.verified?'✓ Verified':''}</span></div><h3>${p.title}</h3><div class="meta"><span>${p.creator}</span><span class="price">€${p.price.toFixed(2)}</span></div><button class="primary buy" onclick="add(${p.id})">Kosárba teszem</button></div></article>`).join('')}
function add(id){const p=state.products.find(x=>x.id===id);const old=state.cart.find(x=>x.id===id);if(old)old.qty++;else state.cart.push({id:p.id,title:p.title,creator:p.creator,price:p.price,qty:1});save();toast('Termék hozzáadva a kosárhoz');}
function renderCart(){const count=state.cart.reduce((a,x)=>a+x.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=state.cart.length?state.cart.map(x=>`<div class="cartRow"><div><b>${x.title}</b><div class="meta">${x.creator} · ${x.qty} db</div></div><strong>€${(x.price*x.qty).toFixed(2)}</strong></div>`).join(''):'<div class="empty">A kosarad még üres.</div>';$('#cartTotal').textContent='€'+state.cart.reduce((a,x)=>a+x.price*x.qty,0).toFixed(2)}
function openDrawer(){$('#drawer').classList.add('open');$('#backdrop').classList.add('show')}function closeDrawer(){$('#drawer').classList.remove('open');$('#backdrop').classList.remove('show')}
async function checkout(){if(!state.cart.length)return toast('A kosár üres');showModal(`<div class="modal"><h2>Demo checkout</h2><p class="muted">Élesítéshez Stripe/Adyen-kompatibilis fizetési szolgáltató és a platform szabályainak megfelelő merchant account szükséges.</p><form class="form" id="checkoutForm"><label>E-mail</label><input required type="email" placeholder="you@example.com"><label>Ország</label><select><option>Magyarország</option><option>Németország</option><option>Ausztria</option></select><button class="primary big full">Demo rendelés leadása</button></form></div>`);$('#checkoutForm').onsubmit=async e=>{e.preventDefault();const email=e.target.querySelector('input').value;const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,items:state.cart})});const d=await r.json();state.cart=[];save();closeModal();closeDrawer();toast('Rendelés létrehozva: '+d.orderId)}}
function showModal(html){$('#modalRoot').innerHTML=`<div class="overlay" id="modalOverlay">${html}</div>`}function closeModal(){$('#modalRoot').innerHTML=''}
function login(){showModal(`<div class="modal"><h2>Belépés</h2><form class="form" onsubmit="event.preventDefault();closeModal();toast('Demo belépés sikeres')"><label>E-mail</label><input required type="email"><label>Jelszó</label><input required type="password"><button class="primary big full">Belépés</button></form></div>`)}
function creatorProfile(name){showModal(`<div class="modal"><div class="eyebrow">VERIFIED CREATOR</div><h2>${name}</h2><p class="muted">Creator storefront • limitált dropok • diszkrét fulfillment</p><button class="primary big full" onclick="closeModal();toast('Creator követve')">Követem</button></div>`)}
function creatorApply(){showModal(`<div class="modal"><h2>Creator jelentkezés</h2><p>Az éles platformon KYC, 18+ ellenőrzés és tartalommoderáció szükséges.</p><form class="form" id="creatorForm"><label>Megjelenő név</label><input required><label>E-mail</label><input required type="email"><label>Social profil</label><input required placeholder="https://..."><button class="primary big full">Jelentkezés beküldése</button></form></div>`);$('#creatorForm').onsubmit=async e=>{e.preventDefault();const inputs=e.target.querySelectorAll('input');await fetch('/api/creators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:inputs[0].value,email:inputs[1].value,social:inputs[2].value})});closeModal();toast('Jelentkezés elküldve')}}
$('#enter').onclick=()=>{localStorage.setItem('vd_age','1');$('#ageGate').remove()};$('#leave').onclick=()=>{document.body.innerHTML='<main style="padding:15vh 8vw;text-align:center"><h1>Viszlát.</h1><p>Az oldal használatához 18+ életkor szükséges.</p></main>'};if(localStorage.getItem('vd_age'))$('#ageGate').remove();
$('#cartBtn').onclick=openDrawer;$('#loginBtn').onclick=login;$('#creatorBtn').onclick=creatorApply;document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.cat)});
fetch('/api/products').then(r=>r.json()).then(d=>{state.products=d;renderProducts();renderCart()}).catch(()=>{state.products=[];renderProducts();renderCart()});
